# Generated by Django 3.2.4 on 2021-06-12 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0002_alter_teamdata_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 10, 30, 8, 243401)),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='team_members',
            field=models.TextField(default='John Doe'),
        ),
    ]
