# Generated by Django 3.2.4 on 2021-06-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0004_auto_20210612_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team_id',
            field=models.CharField(default='ITS200001', max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team_members',
            field=models.TextField(default='John Doe, Jane Doe'),
        ),
    ]
