# Generated by Django 3.2.4 on 2021-06-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('team_name', models.CharField(max_length=220)),
                ('team_id', models.CharField(default='ITS200001', max_length=9, primary_key=True, serialize=False)),
                ('team_members', models.TextField(default='John Doe, Jane Doe')),
            ],
        ),
    ]
